### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/furima-29724#11]
自身のフリマアプリのURL
https://furima-29724.herokuapp.com/

Basic認証のIDとパスワード：
・ID                 admin
・PASS           2222

出品者用のメールアドレスとパスワード
・ADDRESS   furima11@mail
・PASS           furima11

購入者用のメールアドレスとパスワード
・ADDRESS   furima22@mail
・PASS           furima22

購入用カードの番号・期限・セキュリティコード
・Num   4242424242424242
・Exp     12/24
・cvc     123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by k-kudo-hub** [comment]
お忙しいところレビューいただきありがとうございます！
今後ともよろしくお願い致します！
